name: Run tests and deploy if succesfull

on: push
jobs:
  
  # setup python and dependencies to run tests using pytest.
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  
  # if all tests are succesfull, connect to VPS, run script on server to initiate ssh agent, add ssh key used
  # for github acces, pull from git, and restart application.
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SECRET }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/SERVER-GITHUB-PULL
            cd /home/winc-cd/
            git pull
            git status
            systemctl restart winc-cd