name: Run tests and deploy if succesfull

on: push
jobs:
  
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 188.166.40.219
          username: root
          key: ${{ secrets.SERVER_SECRET }}
          port: 22
          script_stop: true
          script: |
            cd /home/winc-cd/
            git pull
            git status