name: Run tests and deploy if succesfull

on: push
jobs:
  
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  
  deploy:
    needs: run-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to server
        run: | 
          ssh root@188.166.40.219
          ${{ secrets.SERVER_ACCES }}
          cd /home/winc-cd/
          git pull
